name: s3sync

on:
  push:
    branches:
    - testnet

# on:
#   push:
#     branches:
#       - main
#   pull_request:
#     types:
#       - opened
#       - synchronize
#     branches:
#       - main

jobs:
  s3_sync_files:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-west-1

      - name: Copy files to the s3 website content bucket
        run: |
          sed -i -e 's#main/kart_remote_config.json#testnet/kart_remote_config_testnet.json#g' index.html

          # Sync assets to s3 remote
          s3path=s3://mozart-assets-001/testnet-kart-game
          aws s3 sync --exclude ".git/*" --exclude ".gitignore" ./ $s3path

