name: s3sync

on:
  push:
    branches:
    - staging

jobs:
  s3_sync_files:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-west-1

      - name: Copy files to the s3 website content bucket
        run: |
          aws s3 sync --exclude ".git/*" --exclude ".gitignore" ./ s3://kart-game-staging
